### ISSUE TITLE
Why are there so limited no. of countries?

### ISSUE THREAD

**Issue by aviskarkc10** [gayanvoice/GitHubStats#2]

**Comment by gayanvoice** [comment]
The GitHub Graph API has some limitations on requesting data from GitHub. The number of requests per hour is 5000. If we put 100 users per request, the API send back 502 error. So we have to limit the number of users per request without getting 502 fro server. 10 users per request has advantages, but it has been limited. So to analyze the most contributed users in GitHub the script limited to 1000 users. It's 100 requests. If script put more than 50 countries, it won't work. Because it passes 5000 requests limit. But I have been working on adding more countries in to the script by put some time delays.

**Comment by gayanvoice** [comment]
Added HTTPS app https://githubstats-com.herokuapp.com/ and added few other countries including Asia, Europe regions
